#!/usr/bin/env python3
# Integrantes do grupo (ordem alfabetica):
# Joao Victor Balvedi - @JoaoVictorBalvedi
#
# Nome do grupo no Canvas: RA1 22

from main import main


if __name__ == "__main__":
    main()
